pipelines:
  default:
    - step:
        name: Php7.1.12
        image: php:7.1.12
        caches:
          - composer
        script:
          - echo "ssh-rsa $PHC_KEY" >> ~/.ssh/authorized_keys
          - apt-get update
          - apt-get install -y git
          - apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --no-custom-installers
          - vendor/bin/phpunit
    - step:
        name: Php7.0.26
        image: php:7.0.26
        caches:
          - composer
        script:
          - apt-get update
          - apt-get install -y git
          - apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --no-custom-installers
          - vendor/bin/phpunit
    - step:
        name: Php5.6.32
        image: php:5.6.32
        caches:
          - composer
        script:
          - apt-get update
          - apt-get install -y git
          - apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --no-custom-installers
          - vendor/bin/phpunit
    - step:
        name: PHPCompatibility 5.4
        image: php:5.6.32
        caches:
          - composer
        script:
          - apt-get update
          - apt-get install -y git
          - apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --no-custom-installers
          - vendor/bin/phpcs --report=code --standard=PHPCompatibility --runtime-set testVersion 5.4 inc/
    - step:
        name: PHPCompatibility 5.3
        image: php:5.6.32
        caches:
          - composer
        script:
          - apt-get update
          - apt-get install -y git
          - apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --no-custom-installers
          - vendor/bin/phpcs --report=code --standard=PHPCompatibility --runtime-set testVersion 5.3 inc/